name: guardian
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  intl: ^0.18.1
  speech_to_text: ^6.5.1
  location: ^5.0.3
  permission_handler: ^11.2.0
  just_audio: ^0.9.36
  http: ^0.13.3
  another_audio_recorder: ^1.1.0
  path_provider: ^2.1.2
  firebase_storage: ^11.6.0
  mailer: ^6.0.1
  google_maps_flutter: ^2.5.3
  telephony: ^0.2.0
  perfect_volume_control: ^1.0.5
  flutter_volume_controller: ^1.3.1
  google_fonts: ^4.0.1
  google_maps_webservice: ^0.0.19
  flutter_google_places: ^0.3.0
  google_maps_webservice_ex: ^0.0.1+2
  flutter_background_service: ^5.0.5
  workmanager: ^0.5.2
  flutter_foreground_service: ^0.4.1
  background_sms: ^0.0.4







dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
  - assets/images/wings.jpg
  - assets/images/wings.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
